---
# tasks file for containerserver_boxfuse
- name: Ensure container is present on host and running
    docker_container:
      #name: "{{ boxfuse_docker_container }}"
      name: boxfuse-webapp
      #image: "{{ boxfuse_docker_image }}"
      iamege: mas0lik/boxfuse-webapp:latest
      state: started
      ports:
        - "8070:8070"