---
# tasks file for imagebuilder_boxfuse
- name: Copy Dockerfile
  copy:
    src: 'Dockerfile'
    dest: '{{ dest_dockerfile_path }}/Dockerfile'
    mode: '0555'

- name: Build an image and push it to a private repo
  docker_image:
    build:
      path: '{{ dest_dockerfile_path }}'
    name: '{{ boxfuse_docker_image }}'
    push: yes
    source: build