---
# tasks file for imagebuilder_boxfuse
- name: Ensure Dockerfile is present on targeted host
  copy:
    src: 'Dockerfile'
    dest: '{{ dest_dockerfile_path }}'
    mode: '0555'

- name: Build an image using supplied Dockerfile and push it to a private repo
  docker_image:
    build:
      path: '{{ dest_dockerfile_path }}'
    name: '{{ boxfuse_docker_image }}'
    push: yes
    source: build